# -*- coding: utf-8 -*-
"""ML-Assignment-4-Classification Problem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G23JUI0ToAqL1VigNjiq_YNHNTn8Rcoc

## Loading and Preprocessing
"""

from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

# Load dataset
data = load_breast_cancer()

#Convert to DataFrame
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target  # Add the target column (0 = malignant, 1 = benign)

#Show basic info
df.info()

#Check for missing values
print(df.isnull().sum())

# Separate features and target
X = df.drop('target', axis=1)
y = df['target']

# Apply StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""## Classification Algorithm Implementation"""

# Import libraries
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Load dataset
data = load_breast_cancer()
X = data.data
y = data.target

# Feature scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

#Logistic Regression
from sklearn.linear_model import LogisticRegression
model_lr = LogisticRegression()
model_lr.fit(X_train, y_train)

"""Uses a sigmoid function to estimate the probability of class membership. Suitable for binary classification.
Breast cancer is binary (Malignant or Benign).
It provides probabilistic outputs and is easy to interpret.
"""

#Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
model_dt = DecisionTreeClassifier(random_state=42)
model_dt.fit(X_train, y_train)

"""Splits data by asking "yes/no" questions building a tree of decisions.
Handles non-linear patterns
Easy to visualize and interpret
Works without scaling (but we already scaled for consistency)
"""

#Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier(n_estimators=100, random_state=42)
model_rf.fit(X_train, y_train)

"""An ensemble of decision trees. Each tree votes, and the majority wins.
Reduces overfitting
Handles large feature sets well
Often gives state-of-the-art performance for tabular data
"""

# Support Vector Machine (SVM)
from sklearn.svm import SVC
model_svm = SVC(kernel='rbf')
model_svm.fit(X_train, y_train)

"""Finds the optimal hyperplane that separates classes with maximum margin.
Very effective in high-dimensional spaces
Works well with clear margin of separation, like in medical data


"""

#k-Nearest Neighbors (k-NN)
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn.fit(X_train, y_train)

"""Classifies a new point by the majority class of its k closest neighbors.
Simple and non-parametric
Good when the data is well-separated and not too large
"""

from sklearn.metrics import accuracy_score, classification_report

models = {
    "Logistic Regression": model_lr,
    "Decision Tree": model_dt,
    "Random Forest": model_rf,
    "SVM": model_svm,
    "k-NN": model_knn
}

for name, model in models.items():
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"🔍 {name} — Accuracy: {acc:.4f}")
    print(classification_report(y_test, y_pred, target_names=data.target_names))
    print("-" * 60)