# -*- coding: utf-8 -*-
"""ML-Assignment 1 - Statistical Measures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qrlG7hHEkDFYOAa56xEQLhBAhyTCJkQW
"""

import pandas as pd

df = pd.read_csv('house_price.csv')
df.head()

"""# Basic **EDA**"""

# Basic Info
df.info()

# Summary Stats
df.describe()

# Check Missing Values
print("\nMissing values:\n", df.isnull().sum())

# Column Names
print("\nColumns:", df.columns.tolist())

"""# **Detect and Remove Outliers**"""

#Mean and Standard Deviation
mean = df['price_per_sqft'].mean()
std = df['price_per_sqft'].std()
df_mean_std = df[(df['price_per_sqft'] >= mean - 3*std) & (df['price_per_sqft'] <= mean + 3*std)]

#Percentile Method

lower_percentile = df['price_per_sqft'].quantile(0.01)
upper_percentile = df['price_per_sqft'].quantile(0.99)

df_percentile = df[(df['price_per_sqft'] >= lower_percentile) & (df['price_per_sqft'] <= upper_percentile)]

#IQR Method
Q1 = df['price_per_sqft'].quantile(0.25)
Q3 = df['price_per_sqft'].quantile(0.75)
IQR = Q3 - Q1

df_iqr = df[(df['price_per_sqft'] >= Q1 - 1.5*IQR) & (df['price_per_sqft'] <= Q3 + 1.5*IQR)]

#Z-score Method
z_scores = np.abs(stats.zscore(df['price_per_sqft']))
df_zscore = df[(z_scores < 3)]

"""# **Boxplot for Comparison**"""

plt.figure(figsize=(14, 8))

plt.subplot(2, 3, 1)
sns.boxplot(x=df['price_per_sqft'])
plt.title('Original')

plt.subplot(2, 3, 2)
sns.boxplot(x=df_mean_std['price_per_sqft'])
plt.title('Mean & Std')

plt.subplot(2, 3, 3)
sns.boxplot(x=df_percentile['price_per_sqft'])
plt.title('Percentile')

plt.subplot(2, 3, 4)
sns.boxplot(x=df_iqr['price_per_sqft'])
plt.title('IQR')

plt.subplot(2, 3, 5)
sns.boxplot(x=df_zscore['price_per_sqft'])
plt.title('Z-score')

plt.tight_layout()
plt.show()

"""# **Histogram, Skewness & Transformation**"""

# Histplot Before
sns.histplot(df['price_per_sqft'], kde=True)
plt.title("Before Transformation")
plt.show()

# Skewness & Kurtosis
print("Skewness Before:", skew(df['price_per_sqft']))
print("Kurtosis Before:", kurtosis(df['price_per_sqft']))

# Log Transform
df['log_price_per_sqft'] = np.log1p(df['price_per_sqft'])

# Histplot After
sns.histplot(df['log_price_per_sqft'], kde=True)
plt.title("After Log Transformation")
plt.show()

# After Skewness & Kurtosis
print("Skewness After:", skew(df['log_price_per_sqft']))
print("Kurtosis After:", kurtosis(df['log_price_per_sqft']))

"""# **Correlation & Heatmap**"""

plt.figure(figsize=(10, 6))
correlation = df.corr(numeric_only=True)
sns.heatmap(correlation, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

"""# **Scatter Plots Between Variables**"""

# Get all numeric columns
numeric_cols = df.select_dtypes(include=np.number).columns.tolist()

# Scatter Plots
for col in numeric_cols:
    if col != 'price_per_sqft':
        sns.scatterplot(data=df, x=col, y='price_per_sqft')
        plt.title(f'{col} vs Price per Sqft')
        plt.show()