# -*- coding: utf-8 -*-
"""ML_Assignment_2_EDA_and_Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14iwV_rDZYT48T-FpsF7rJsW8U3grCBNU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler, MinMaxScaler

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('Employee.csv')
df.head()

"""# **Explore the Data**"""

# Check data types and basic info
df.info()

# Show unique values in each column and their count
for col in df.columns:
    print(f"Column: {col}")
    print("Unique Values:", df[col].unique())
    print("Count of Unique Values:", df[col].nunique())
    print("-" * 40)

# Statistical Summary
df.describe(include='all')

"""# **Data Cleaning**"""

#Rename Columns (if needed)
df.columns = [col.strip().lower().replace(' ', '_') for col in df.columns]
df.head()

# Total missing values per column
print("Missing values:\n", df.isnull().sum())

#Replace Age = 0 with NaN
df['age'] = df['age'].replace(0, np.nan)

#Remove Duplicate Rows
df = df.drop_duplicates()

# Fill Missing Values (mean for numeric, mode for categorical)
for col in df.columns:
    if df[col].dtype == 'object':
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:
        df[col].fillna(df[col].median(), inplace=True)

#Outlier Detection (using IQR Method)

def remove_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    return data[(data[column] >= Q1 - 1.5 * IQR) & (data[column] <= Q3 + 1.5 * IQR)]

# Example: remove outliers from 'salary'
if 'salary' in df.columns:
    df = remove_outliers_iqr(df, 'salary')

"""# **Data Analysis**"""

#Filter: Age > 40 and Salary < 5000
filtered_df = df[(df['age'] > 40) & (df['salary'] < 5000)]
print(filtered_df)

#Plot Age vs Salary
sns.scatterplot(data=filtered_df, x='age', y='salary')
plt.title("Age vs Salary (Filtered)")
plt.xlabel("Age")
plt.ylabel("Salary")
plt.show()

# Count People from Each Place
if 'place' in df.columns:
    place_counts = df['place'].value_counts()
    place_counts.plot(kind='bar')
    plt.title("Count of People from Each Place")
    plt.xlabel("Place")
    plt.ylabel("Count")
    plt.xticks(rotation=45)
    plt.show()

"""# **Data Encoding**"""

#Label Encoding (for binary categoricals)

label_enc = LabelEncoder()
for col in df.select_dtypes(include='object').columns:
    if df[col].nunique() == 2:
        df[col] = label_enc.fit_transform(df[col])

# One-Hot Encoding (for multi-class categoricals)
df = pd.get_dummies(df, drop_first=True)

"""# **Feature Scaling**"""

#StandardScaler

scaler_std = StandardScaler()
scaled_std = scaler_std.fit_transform(df)

df_std = pd.DataFrame(scaled_std, columns=df.columns)
print("\nStandard Scaled Data:\n")
print(df_std.head())

#MinMaxScaler
scaler_mm = MinMaxScaler()
scaled_mm = scaler_mm.fit_transform(df)

df_mm = pd.DataFrame(scaled_mm, columns=df.columns)
print("\nMin-Max Scaled Data:\n")
print(df_mm.head())