# -*- coding: utf-8 -*-
"""ML_Assignment_3-Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m5BLu62In5NwNzjqxLoUVQ3UWxwHFIxN
"""

from sklearn.datasets import fetch_california_housing
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split

# 🔄 Step 2: Load the California Housing Dataset
california = fetch_california_housing()

# 🔃 Step 3: Convert to Pandas DataFrame
df = pd.DataFrame(california.data, columns=california.feature_names)
df['MedHouseVal'] = california.target  # Add target column (Median House Value)

# 👀 Step 4: Display first few rows
df.head()

"""## **Check for Missing Values**"""

# Check if any missing values exist
print(df.isnull().sum())

#Feature Scaling (Standardization)

from sklearn.preprocessing import StandardScaler

# Separate features and target
X = df.drop('MedHouseVal', axis=1)
y = df['MedHouseVal']

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""# **Regression Algorithm Implementation**"""

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, r2_score

# Store models and names
models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(n_estimators=100, random_state=42),
    "Support Vector Regressor": SVR()
}

# Evaluate each model
results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    results.append({
        "Model": name,
        "MSE": round(mse, 3),
        "R² Score": round(r2, 3)
    })


    results_df = pd.DataFrame(results)
results_df.sort_values(by="R² Score", ascending=False)

"""# Linear Regression
How it works: Fits a straight line to predict the target as a linear combination of features.

Suitable because: It’s simple, fast, and often a good baseline. Works well when relationships are linear.

# Decision Tree Regressor
How it works: Splits the data into regions using feature thresholds; each region predicts the mean target value.

Suitable because: Can capture non-linear relationships and interactions between features.

# Random Forest Regressor
How it works: An ensemble of decision trees where each tree is trained on a subset of the data and features. Final prediction is averaged.

Suitable because: Handles complex patterns, reduces overfitting, and is robust to noise.

# Gradient Boosting Regressor
How it works: Sequentially builds trees where each new tree corrects the error of the previous one.

Suitable because: Excellent for tabular data and captures subtle patterns, often better than Random Forests in performance.

# Support Vector Regressor (SVR)
How it works: Attempts to fit the best line (or hyperplane) within a margin. Can use kernels for non-linear regression.

Suitable because: Works well for small- to medium-sized datasets with complex relationships. May require scaling.


"""



"""Evaluate the performance of each algorithm using the following metrics: Mean Squared Error (MSE) Mean Absolute Error (MAE) R-squared Score (R²) Compare the results of all models and identify: The best-performing algorithm with justification. The worst-performing algorithm with reasoning."""

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Reuse the models dictionary from before
models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(n_estimators=100, random_state=42),
    "Support Vector Regressor": SVR()
}

# Evaluate and store results
metrics = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    metrics.append({
        'Model': name,
        'MSE': round(mse, 3),
        'MAE': round(mae, 3),
        'R²': round(r2, 3)
    })

# Display results in a table
metrics_df = pd.DataFrame(metrics).sort_values(by="R²", ascending=False)
metrics_df

"""***Best-Performing Algorithm: Gradient Boosting Regressor***
Highest R² score (≈ 0.83) — it explains 83% of the variance in house prices.
Lowest MSE and MAE — best at minimizing both average and squared errors.
Gradient Boosting builds models sequentially to fix previous errors, making it very powerful for complex tabular data like housing.

***Worst-Performing Algorithm: Support Vector Regressor (SVR)***
Lowest R² score (~0.45), poor variance explanation.
Highest error rates (both MSE and MAE).
SVR doesn’t scale well with large datasets, and it’s sensitive to feature scaling and hyperparameters. It’s better suited for smaller or very clean datasets.


"""